//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImobilidadeFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imovel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imovel()
        {
            this.Negocio = new HashSet<Negocio>();
        }
    
        public int IdImovel { get; set; }
        public string Vagas { get; set; }
        public string Quartos { get; set; }
        public string Suite { get; set; }
        public string Area { get; set; }
        public string ValorTotal { get; set; }
        public int IdProprietario { get; set; }
        public int IdBairro { get; set; }
        public int IdTipoImovel { get; set; }
    
        public virtual Bairro Bairro { get; set; }
        public virtual Proprietario Proprietario { get; set; }
        public virtual TipoImovel TipoImovel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio> Negocio { get; set; }
    }
}
