//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImobilidadeFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImovelBDEntities : DbContext
    {
        public ImovelBDEntities()
            : base("name=ImovelBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bairro> Bairro { get; set; }
        public virtual DbSet<Imovel> Imovel { get; set; }
        public virtual DbSet<Negocio> Negocio { get; set; }
        public virtual DbSet<Proprietario> Proprietario { get; set; }
        public virtual DbSet<TipoImovel> TipoImovel { get; set; }
        public virtual DbSet<TipoNegocio> TipoNegocio { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
