//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImobilidadeFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio
    {
        public string Valor { get; set; }
        public int IdImovel { get; set; }
        public int IdTipoNegocio { get; set; }
    
        public virtual Imovel Imovel { get; set; }
        public virtual TipoNegocio TipoNegocio { get; set; }
    }
}
